[package]
name = "cv-convert"
description = "Type conversions among famous Rust computer vision libraries"
version = "0.12.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2021"
documentation = "https://docs.rs/cv-convert/"
repository = "https://github.com/jerry73204/rust-cv-convert.git"
homepage = "https://github.com/jerry73204/rust-cv-convert/"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
image = { version = "0.23.14", optional = true }
nalgebra = { version = "0.29.0", optional = true }
opencv = { version = "0.60.0", default-features = false, features = ["calib3d"], optional = true }
ndarray = { version = "0.15.3", optional = true }
tch = { version = "0.6.1", optional = true }
slice-of-array = "0.3.1"
half = "1.8.2"

[dev-dependencies]
approx = "0.5.0"
itertools = "0.10.1"
rand = "0.8.4"

[features]
default = []
full = ["image", "opencv", "tch", "nalgebra", "ndarray"]
docs-only = ["full", "opencv/docs-only", "tch", "tch/doc-only", "image", "nalgebra", "ndarray"]
opencv-clang-runtime = ["opencv/clang-runtime"]

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
