[package]
name = "cv-convert"
description = "Type conversions among famous Rust computer vision libraries"
version = "0.4.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/cv-convert/"
repository = "https://github.com/jerry73204/rust-cv-convert.git"
homepage = "https://github.com/jerry73204/rust-cv-convert/"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
image = { version = "0.23.14", optional = true }
nalgebra = { version = "0.25.3", optional = true }
opencv = { version = "0.51.0", default-features = false, optional = true }
ndarray = { version = "0.15.1", optional = true }
tch = { version = "0.4.0", optional = true }

[dev-dependencies]
approx = "0.4.0"
itertools = "0.10.0"
rand = "0.8.3"

[features]
default = ["image", "opencv-4", "opencv-buildtime-bindgen", "tch", "nalgebra", "ndarray"]
docs-only = ["opencv-4", "opencv-contrib", "opencv/docs-only", "tch", "tch/doc-only", "image", "nalgebra", "ndarray"]
opencv-4 = ["opencv", "opencv/opencv-4"]
opencv-34 = ["opencv", "opencv/opencv-34"]
opencv-32 = ["opencv", "opencv/opencv-32"]
opencv-contrib = ["opencv", "opencv/contrib"]
opencv-buildtime-bindgen = ["opencv", "opencv/buildtime-bindgen"]

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
