[package]
name = "cv-convert"
description = "Type conversions among famous Rust computer vision libraries"
version = "0.2.2"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/cv-convert/"
repository = "https://github.com/jerry73204/rust-cv-convert.git"
homepage = "https://github.com/jerry73204/rust-cv-convert/"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
image = { version = "0.23.12", optional = true }
nalgebra = { version = "0.24.0", optional = true }
opencv = { version = "0.48.0", default-features = false, optional = true }
tch = { version = "0.3.1", optional = true }

[dev-dependencies]
approx = "0.4.0"
rand = "0.8.2"

[features]
default = ["image", "opencv-4", "opencv-buildtime-bindgen", "tch", "nalgebra"]
## due to issue on opencv-rust, disable opencv in docs-only for now
## https://github.com/twistedfall/opencv-rust/issues/199
# docs-only = ["opencv-4", "opencv-contrib", "opencv/docs-only", "tch", "tch/doc-only", "image", "nalgebra"]
docs-only = ["tch", "tch/doc-only", "image", "nalgebra"]
opencv-4 = ["opencv", "opencv/opencv-4"]
opencv-34 = ["opencv", "opencv/opencv-34"]
opencv-32 = ["opencv", "opencv/opencv-32"]
opencv-contrib = ["opencv", "opencv/contrib"]
opencv-buildtime-bindgen = ["opencv", "opencv/buildtime-bindgen"]


[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
